services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
